src/ecommerce_crm/suspense/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic import TemplateView

urlpatterns = patterns('ecommerce_crm.suspense.views',
                   url(r'^add_distance', 'add_distance'),
                   url(r'^clresult/','clearance_result'),
                   url(r'^clsearch/','clearance_search'),
                   url(r'^othercharges/','other_charges'),
                   url(r'^tada_result/','tada_result'),
                   url(r'^tada_order_session/','tada_order_session'),
                   url(r'^with_transport/','with_transport'),
                   url(r'^transport/', 'transport'),
                   url(r'^transportbill/', 'transportbill'),
                   url(r'^quoted_add_distance', 'quoted_add_distance'),
                   url(r'^quoted_save_distance', 'quoted_save_distance'),
                   url(r'^save_distance', 'save_distance'),
                   url(r'^sessionselect/', 'sessionselect'),
                   url(r'^mark_clear/', 'mark_clear'),
                   url(r'^mark_status/', 'mark_status'),
                   url(r'^clearance_options/', 'clearance_options'),
                   url(r'^summary_page/','summary_page'),                   
                   url(r'^transport_bill/','transport_bill'),                   
                   url(r'^tada_bill/','tada_bill'),
                   url(r'^tada_bill_list/','tada_bill_list'),
                   url(r'^car_taxi_advance_form/','car_taxi_advance_form'),
                   url(r'^car_taxi_advance/','car_taxi_advance')
              )                    
        

src/ecommerce_crm/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from reports.register_generator import GenerateRegister
from reports.search import SearchResult
from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'ecommerce_crm.catalog.views.index', name='home'),
    url(r'^catalog/', include('ecommerce_crm.catalog.urls')),
    url(r'^useraccounts/', include('useraccounts.urls')),
    url(r'^print/', include('ecommerce_crm.prints.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/','ecommerce_crm.reports.views.search_form'),
    url(r'^search_result/', SearchResult.as_view(), name='search_result'),
    url(r'^save_fields', 'ecommerce_crm.reports.views.save_fields'),
    url(r'^list_saved_registers', 'ecommerce_crm.reports.views.list_saved_registers'),
    url(r'daily_result', 'ecommerce_crm.reports.register.daily_report_result', name='daily_report_result'),
    url(r'consultancy_funds_report', 'ecommerce_crm.reports.register.consultancy_funds_report', name='consultancy_funds_report'),    
    url(r'tds_report', 'ecommerce_crm.reports.register.tds_report_result', name='tds_report_result'),    
    url(r'payment_report', 'ecommerce_crm.reports.register.payment_register', name='payment_register'),
    url(r'suspense_clearance_register', 'ecommerce_crm.reports.register.suspense_clearance_register'),
    url(r'servicetax', 'ecommerce_crm.reports.register.servicetax_register'),
    url(r'^main_register', 'ecommerce_crm.reports.register.main_register', name='main_register'),
    url(r'^proforma_register', 'ecommerce_crm.reports.register.proforma_register'),
    url(r'^non_payment_register', 'ecommerce_crm.reports.register.non_payment_register'),
    url(r'^client_register', 'ecommerce_crm.reports.register.client_register', name='client_register'),
    url(r'^material_report', 'ecommerce_crm.reports.register.material_report'),
    url(r'^lab_report', 'ecommerce_crm.reports.register.lab_report'),
    url(r'^suspense_register', 'ecommerce_crm.reports.register.suspense_register'),
    url(r'^registered_users', 'ecommerce_crm.reports.register.registered_users'),
    url(r'^filter_sub_category/', 'ecommerce_crm.reports.views.filter_sub_category'),
    url(r'^bill/', 'ecommerce_crm.prints.views.bill'),
    url(r'^suspense_bill/', 'ecommerce_crm.prints.views.suspense_bill'),
    url(r'^quoted_bill/', 'ecommerce_crm.prints.views.quoted_bill'),
    url(r'^tax/', 'ecommerce_crm.prints.views.tax'),
    url(r'^bills/', include('ecommerce_crm.bills.urls')),
    url(r'^suspense/', include('ecommerce_crm.suspense.urls')),
    url(r'^generate_register/', GenerateRegister.as_view(), name='view_register'),
    url(r'^history/','ecommerce_crm.reports.previous_history.history'),
    url(r'^details/','ecommerce_crm.reports.previous_history.details'),
    url(r'^proforma_details/','ecommerce_crm.reports.previous_history.proforma_details'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^voucher/', include('ecommerce_crm.voucher.urls')),
    url(r'^receipt/', 'ecommerce_crm.prints.views.receipt'),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^programmeletter/', 'ecommerce_crm.programmeletter.views.programmeletter'),
    url(r'pending_clearance_register', 'ecommerce_crm.reports.register.pending_clearance_register'),
    url(r'tada_register', 'ecommerce_crm.reports.register.tada_register'),
    url(r'tada_othercharges_register', 'ecommerce_crm.reports.register.tada_othercharges_register'),
    url(r'client_details_according_to_amount', 'ecommerce_crm.reports.register.client_details_according_to_amount'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

src/ecommerce_crm/suspense/models.py
from django.db import models
import datetime

from ecommerce_crm.voucher.models import VoucherId
from ecommerce_crm.voucher.models import FinancialSession

from ecommerce_crm.bills.models import QuotedOrder

from ecommerce_crm.catalog.models import PurchaseOrder, Category

import simplejson


class SuspenseOrder(models.Model):
    """
    Stores order with over head costs.
    """
    voucher = models.IntegerField()
    purchase_order = models.ForeignKey(PurchaseOrder)
    session_id = models.ForeignKey(FinancialSession)
    distance_estimated = models.IntegerField(default=0)
    is_cleared = models.BooleanField(default=False)
    def __unicode__(self):
        return '%s' % (self.id)


class SuspenseClearance(models.Model):
    """
    Stores clearance of suspense orders.
    """
    session = models.ForeignKey(FinancialSession)
    voucher_no = models.IntegerField()
    work_charge =models.IntegerField(blank=True, null=True)
    labour_charge = models.IntegerField(blank=True, null=True)
    car_taxi_charge = models.IntegerField(blank=True, null=True)
    boring_charge_external = models.IntegerField(blank=True, null=True)
    boring_charge_internal = models.IntegerField(blank=True, null=True)
    lab_testing_staff = models.CharField(max_length=200, blank=True, null=True)
    field_testing_staff = models.CharField(max_length=200,blank=True,null=True)
    test_date = models.CharField(max_length=600, blank=True, null=True)
    clear_date = models.DateField()


class Department(models.Model):
    """
    Stores department.
    """
    title = models.CharField(max_length=50)
    address = models.CharField(max_length=150)
    phone = models.CharField(max_length=20, blank=True)
    dean = models.CharField(max_length=50, blank=True)
    def __unicode__(self):
        return self.title

class StaffPosition(models.Model):
    """
    Stores position of staff.
    """
    position = models.CharField(max_length=50)
    rank = models.IntegerField()

    def __unicode__(self):
        return self.position

class Staff(models.Model):
    """
    Stores staff and map it with position.
    """
    department = models.ForeignKey(Department)
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=50)
    daily_ta_da = models.IntegerField(blank=True)
    position = models.ForeignKey(StaffPosition)
    seniority_credits = models.IntegerField()
    always_included = models.BooleanField(default=True)
    lab = models.ForeignKey(Category)
    email =models.EmailField(blank=True)

    class Meta:
        verbose_name_plural = "Staff"

    def __unicode__(self):
        return self.name


class TaDa(models.Model):
    """
    Model to store transport and daily allowances.
    """
    date_of_generation = models.DateField(default=datetime.date.today)
    voucher_no = models.IntegerField()
    session = models.IntegerField()
    departure_time_from_tcc= models.TimeField()
    arrival_time_at_site = models.TimeField()
    departure_time_from_site = models.TimeField()
    arrival_time_at_tcc = models.TimeField()
    tada_amount = models.IntegerField()
    start_test_date = models.DateField()
    end_test_date = models.DateField()
    source_site = models.CharField(max_length=100, default = 'GNDEC, Ludhiana')
    testing_site= models.CharField(max_length=100)
    testing_staff = models.CharField(max_length=100)
    def __unicode__(self):
       return self.suspense


class QuotedSuspenseOrder(models.Model):
    """
    Stores Quoted suspense order.
    """
    quoted_order = models.ForeignKey('bills.QuotedOrder')
    distance_estimated = models.IntegerField(default=0)
    is_cleared = models.BooleanField(default=False)
    def __unicode__(self):
        return '%s' % (self.id)


class Vehicle(models.Model):
    """
    Stores vehicle details.
    """
    vehicle_id = models.CharField(max_length=20)
    vehicle_no = models.CharField(max_length=20)
    vehicle_name = models.CharField(max_length=20)
    def __unicode__(self):
        return '%s' % (self.vehicle_no)


class Transport(models.Model):
    """
    Stores Transportation details.
    """
    vehicle = models.ForeignKey(Vehicle)
    kilometer = models.CharField(max_length=500)
    rate = models.FloatField(default=10.0)
    date_of_generation = models.DateField()
    date = models.CharField(blank=True, max_length=600)
    total = models.IntegerField()
    voucher_no = models.IntegerField()
    session = models.ForeignKey(FinancialSession)
    '''def save(self, *args, **kwargs):

        # Now decode the kilometers
        jsonkilometer = simplejson.loads(self.kilometer)
        total_km = 0;

        # calculate the total kms
        for km in jsonkilometer:
            total_km += float(km)

        # Now calculate the total and save it in model
        self.total = total_km * self.rate
        super(Transport, self).save(*args, **kwargs)
    '''

    class Meta:
        verbose_name_plural = "Transport"

    def __unicode__(self):
        return '%s' % (self.vehicle)


class TransportBillOfSession(models.Model):
    transport = models.ForeignKey(Transport)
    transportbillofsession = models.IntegerField()
    session = models.ForeignKey(FinancialSession)


class SuspenseClearedRegister(models.Model):
    suspenseclearednumber = models.IntegerField()
    voucher_no = models.IntegerField()
    session = models.ForeignKey(FinancialSession)


class CarTaxiAdvance(models.Model):
    voucher_no = models.IntegerField()
    session = models.ForeignKey(FinancialSession)
    spent = models.IntegerField()
    advance = models.IntegerField()
    balance = models.IntegerField()
    receipt_no = models.IntegerField()
    receipt_session = models.IntegerField()

src/ecommerce_crm/suspense/forms.py
from django.forms import ModelForm, TextInput

from models import SuspenseClearance
from models import TaDa
from models import Staff
from models import SuspenseOrder
from models import QuotedSuspenseOrder
from models import CarTaxiAdvance

from ecommerce_crm.catalog.models import Category

from django import forms

from ecommerce_crm.suspense.models import FinancialSession
from ecommerce_crm.suspense.models import VoucherId
from ecommerce_crm.suspense.models import Vehicle

import datetime


class Clearance_form(ModelForm):
    """
    Form for clearance of order.
    """
    required_css_class = 'required'
    error_css_class = 'error'

    class Meta:
        model = SuspenseClearance
        exclude = ('work_charge',)
        widgets = {'session': forms.HiddenInput(),\
        'voucher_no': forms.HiddenInput()}
    
    def __init__(self, *args, **kwargs):
        super(Clearance_form, self).__init__(*args, **kwargs)
        self.fields['voucher_no'].widget.attrs={'class':'form-control'}
        self.fields['car_taxi_charge'].widget.attrs={'class':'form-control'}
        self.fields['labour_charge'].widget.attrs={'class':'form-control'}
        self.fields['boring_charge_external'].widget.attrs={'class':'form-control'}
        self.fields['boring_charge_internal'].widget.attrs={'class':'form-control'}
        self.fields['lab_testing_staff'].widget.attrs={'class':'form-control'}
        self.fields['field_testing_staff'].widget.attrs={'class':'form-control'}
        self.fields['test_date'].widget.attrs={'class':'form-control'}
        self.fields['clear_date'].widget.attrs={'class':'form-control'}
        self.fields['session'].widget.attrs={'class':'form-control'}

class SuspenseForm(ModelForm):
    required_css_class = 'required'
    error_css_class = 'error'

    class Meta:
        model = SuspenseOrder
        exclude = ('is_cleared',)


class QuotedSuspenseForm(ModelForm):
    class Meta:
        model = QuotedSuspenseOrder
        exclude = ('is_cleared',)


class TaDaSearch(forms.Form):
    """
    Form for TaDa search.
    """
    ref_no = forms.ModelChoiceField(queryset= SuspenseOrder.objects.all())


class TaDaForm(ModelForm):
    """
    Transport and dialy allowance form.
    """
    required_css_class = 'required'
    error_css_class = 'error'

    class Meta:
        model = TaDa
        exclude = ('date_of_generation','tada_amount')
        widgets = {'session': forms.HiddenInput(),\
        'voucher_no': forms.HiddenInput()}
    def __init__(self, *args, **kwargs):
        super(TaDaForm, self).__init__(*args, **kwargs)
        self.fields['voucher_no'].widget.attrs={'class':'form-control'}
        self.fields['session'].widget.attrs={'class':'form-control'}
        self.fields['departure_time_from_tcc'].widget.attrs={'class':'form-control'}
        self.fields['arrival_time_at_site'].widget.attrs={'class':'form-control'}
        self.fields['departure_time_from_site'].widget.attrs={'class':'form-control'}
        self.fields['arrival_time_at_tcc'].widget.attrs={'class':'form-control'}
        self.fields['start_test_date'].widget.attrs={'class':'form-control'}
        self.fields['end_test_date'].widget.attrs={'class':'form-control'}
        self.fields['source_site'].widget.attrs={'class':'form-control'}
        self.fields['testing_site'].widget.attrs={'class':'form-control'}
        self.fields['testing_staff'].widget.attrs={'class':'form-control'}


class StaffForm(forms.ModelForm):
    """
    Form for adding staff.
    """
    class Meta:
        model = Staff
        exclude = []

    try:
        lab = forms.ModelChoiceField(queryset=Category.objects.\
        filter(parent__isnull=True))
    except:
        pass


class SessionSelectForm(forms.Form):
    """
    Form for selection of sessions.
    """
    required_css_class = 'required'
    error_css_class = 'error'
    
    session = forms.ModelChoiceField(queryset=FinancialSession.objects.all())
    voucher = forms.CharField()
    def __init__(self, *args, **kwargs):
        super(SessionSelectForm, self).__init__(*args, **kwargs)
        self.fields['voucher'].widget.attrs={'class':'form-control'}
        self.fields['session'].widget.attrs={'class':'btn btn-default dropdown-toggle'}


class TransportForm1(forms.Form):
    """
    Transport form.
    """
    required_css_class = 'required'
    error_css_class = 'error'
    Vehicle = forms.ModelChoiceField(queryset=Vehicle.objects.all())
    Date_of_generation = forms.DateField(initial = datetime.date.today)
    kilometer = forms.CharField()
    date = forms.DateField(label="Date of visit")
    def __init__(self, *args, **kwargs):
        super(TransportForm1, self).__init__(*args, **kwargs)
        self.fields['Date_of_generation'].widget.attrs={'class':'form-control'}
        self.fields['kilometer'].widget.attrs={'class':'form-control'}
        self.fields['date'].widget.attrs={'class':'form-control'}
        self.fields['Vehicle'].widget.attrs={'class':'btn btn-default dropdown-toggle'}


class CarTaxiAdvance_form(ModelForm):
    """
    Form for clearance of order.
    """
    required_css_class = 'required'
    error_css_class = 'error'

    class Meta:
        model = CarTaxiAdvance
        exclude = ('balance',)
        widgets = {'session': forms.HiddenInput(),\
        'voucher_no': forms.HiddenInput()}

    def __init__(self, *args, **kwargs):
        super(CarTaxiAdvance_form, self).__init__(*args, **kwargs)
        self.fields['spent'].widget.attrs={'class':'form-control'}
        self.fields['advance'].widget.attrs={'class':'form-control'}
        self.fields['receipt_no'].widget.attrs={'class':'form-control'}
        self.fields['receipt_session'].widget.attrs={'class':'form-control'}
        self.fields['receipt_session'] = forms.ChoiceField((o.id, str(o))\
        for o in FinancialSession.objects.all())

src/templates/suspense/add_distance.html
{% extends 'base.html' %}
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>Add Distance</title>
    {% endblock %}
</head>
<body>
  {% block content %}
  <form method = 'POST' class="form-horizontal" action = ''>
      {% csrf_token %}
      <table class='add_distance'>
        <tr>
            <td style="display:none;">Order:<input type="text" name = "order" class = "order" size="7"
             id="order" value="{{purchase_order_id}}">
         </td>
     </tr>
     {% for value in voucher %}
     <tr>
        <td>Vocher:<input type="text" name = "voucher" class = "voucher form-control" size="7"
         id="voucher_{{value.voucher_no}}" value="{{value.voucher_no}}"></td>
         <td>Material:<input type="text" name = "material" class = "material form-control" size="35"
             id="material_{{value.voucher_no}}"
             value="{{value.purchased_item__item__category__name}}"></td>
             <td>Distance:<input type="text" name="distance" class = "distance form-control" size = "7"
                 id="distance_{{value.voucher_no}}" value="0"></td>
             </tr>
             {% endfor %}
         </table>
         <div id="add_distance_div">
         <input type='submit' class="btn btn-info btn-large adddistancesave" value = 'Next'>
        </div>
     </form>
     {% endblock %}
</body>

src/templates/suspense/car_taxi_advance_form.html
{% extends "base.html" %} {% load staticfiles %}

<html>
<head>
    {% block title %}
    <title>Form</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    {% if car_taxi_advance %}
    <form method="POST" action={% url 'ecommerce_crm.suspense.views.car_taxi_advance' %} >
        {% else %}
        <form method="POST" action=''>
            {% endif %}
            {% if messages %}
                <div class="alert alert-success">
                    {{ messages }} 
                </div>
                {% endif %}
            {% csrf_token %}
            <table>
              {% if message %}
              <div class="alert alert-danger">
                  {{ message }}
              </div>
              {% endif %}
              {{form.as_table}}
          </table>
          <input type="submit" class="btn btn-info btn-large" value="Submit" id="button1">
      </form>
      {% endblock %}
  </body>
  </html>

src/templates/suspense/car_taxi_advance_success.html
{% extends 'base_register.html' %}
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Order added</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Values saves <span class='green'>
      Successfully</span></p>
   </div>
   {% endblock %}
</body>
</html>

src/templates/suspense/clearance_options.html
{% extends 'base_register.html' %}
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Clearance Options</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Clearance Options</p>
      <table>
      <tr>
          <th>Order No.</th>
          <td>{{order_id}}</td>
       </tr>
       <tr>
          <th>Voucher No.</th>
          <td>{{voucher_no}}</td>
       </tr>
       <tr>
          <th>Session:</th>
          <td>{{financialsession.session_start_date}} : {{financialsession.session_end_date}}</td>
       </tr>
       <tr>
          <th>Client:</th>
          <td>{{details.buyer__first_name}}&nbsp;{{details.buyer__last_name}}
           &nbsp;{{details.buyer__customer__title}}</td>
       </tr>
       <tr>
           <th>Address:</th>
           <td>{{details.buyer__customer__address__street_address}}&nbsp;
              {{details.buyer__customer__address__district}}</td>
          </tr>
          <tr>
           <th>Mode Of Payment:</th>
           <td>{{details.mode_of_payment__method}}</td>
       </tr>
   </table>
   <div class='order-success-options'>
    <table>
        <tr>
           <th colspan='3'><h3>Options</h3></th>
       </tr>
       <tr>
         {% if with_transport == 0 %}
           <td><a target="_blank" href = '{% url 'ecommerce_crm.suspense.views.with_transport' %}?voucher_no={{voucher_no}}&session={{session_id}}'><input type="button" class="btn btn-info btn-large" name="" value="with transport"></a></td>

           <form id="myForm" action="{% url 'ecommerce_crm.suspense.views.transport_bill' %}" method="post">
           {% csrf_token %}
           <td><input type="submit" class="btn btn-info btn-large" value="Transport Bill"/></td>
             <input type="hidden" value="{{ session_id }}" name="session" />
             <input type="hidden" value="{{ voucher_no }}" name="voucher" />
           </td>
           </form>
          {% else %}
          <td><a  target="_blank" href = '{% url 'ecommerce_crm.suspense.views.with_transport' %}?voucher_no={{voucher_no}}&session={{session_id}}'><input type="button" class="btn btn-info btn-large" name="" value="without transport"></a></td>
          {% endif %}
           <td><a target="_blank" href = '{% url 'ecommerce_crm.suspense.views.other_charges' %}?voucher_no={{voucher_no}}&session={{session_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Other Charges"></a></td>
          
         <form id="myForm" action="{% url 'ecommerce_crm.suspense.views.tada_bill_list' %}" method="post">
           {% csrf_token %}
           <td><input type="submit" class="btn btn-info btn-large" value="TA/DA Bill" name='button1' id='button1' /></td>
             <input type="hidden" value="{{ session_id }}" name="session" />
             <input type="hidden" value="{{ voucher_no }}" name="voucher" />
           </form>

       </tr>
    </table>
       </div>
   </div>
   {% endblock %}
</body>
</html>

src/templates/suspense/clearance_result.html
{% extends "base.html" %} 
<html>
<head>
    {% block title %}
    <title>
        Suspense Job
    </title>
    <style type="text/css">
    .clearance_table{
        width: 200% !important;
        margin-top: 50px;
    }
    </style>
    {% endblock %}
</head>
<body>
    {% block content %}
    <div class='clearance-success'>
        <p class='success-message'>Clearance <span class='green'>
            Successful</span></p></div>
            <div class="clearance_table">
            <table>
                <tr>
                    <th>Session:</th>
                    <td>{{session}}</td>
                </tr>
                <tr>
                    <th>Voucher No.</th>
                    <td>{{voucher_no}}</td>
                </tr>
                <tr>
                    <th>Labour Charge:</th>
                    <td>{{labour_charge}}</td>
                </tr>
                <tr>
                    <th>Car Taxi Charge:</th>
                    <td>{{car_taxi_charge}}</td>
                </tr>
                <tr>
                    <th>Boring Charge External:</th>
                    <td>{{boring_charge_external}}</td>
                </tr>
                <tr>
                    <th>Boring Charge Internal:</th>
                    <td>{{boring_charge_internal}}</td>
                </tr>
                <tr>
                    <th>Lab Testing Staff:</th>
                    <td>{{lab_testing_staff}}</td>
                </tr>
                <tr>
                    <th>field Testing Staff:</th>
                    <td>{{field_testing_staff}}</td>
                </tr>
                <tr>
                    <th>Test Date:</th>
                    <td>{{test_date}}</td>
                </tr>
                <tr>
                    <th>Clear Date:</th>
                    <td>{{clear_date}}</td>
                </tr>
            </table>
            </div>
    {% endblock %}
</body>
</html>

src/templates/suspense/transportform.html
{% extends "base.html" %} 

{% block extrastyle %}
{% endblock %} 

{% block extrajs %}
<script type="text/javascript">
    $(document).ready(function() {
        $("[name='date']").datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        }); 
        $("#button2").click(function() {

        //Insert just after the kilo input in p element
        $("#id_kilometer").parent("p").clone().insertAfter($("#id_date").parent("p"));
        var dateelement = $("#id_date").parent("p").clone();
        var newdateelement = $("<input class='form-control' type='text' name='date' />");

        //We have to replace the date field with new one everytime as browser
        //will confuse it with the cloned element and events will not work
        dateelement.children("input[name='date']").replaceWith(newdateelement);
        dateelement.insertAfter($("#id_date").parent("p"));
        $("[name='date']").datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        }); 
    });
    });
</script>
{% endblock %} 
{% block content %}
<table>
    <tr>
        <td>
            <form action='{% url 'ecommerce_crm.suspense.views.transportbill' %}' method='POST'>
                {% if messages %}
                <div class="alert alert-success">
                    {{ messages }} 
                </div>
                {% endif %}
                {% if message %}
                <div class="alert alert-danger">
                    {{ message }} 
                </div>
                {% endif %}
                {% csrf_token %}
                {{TransportForm.as_p}}
                <input type="hidden" value="{{ session }}" name="session" />
                <input type="hidden" value="{{ voucher }}" name="voucher" />

                <input type="submit" class="btn btn-info btn-large" value="Generate Bill" name='button1' id='button1' />
                <input type="button" class="btn btn-info btn-large" value="Add Another" name='button2' id='button2' />
            </form>
        </td>
    </tr>
</table>
{% endblock %}