src/ecommerce_crm/catalog/urls.py
"""
urls of catalog are..
"""
from django.conf.urls import url, patterns

from django.views.generic import TemplateView


"""
urls showing the list of item purchased and redirects to page of adding 
new categories of product 
"""
urlpatterns = patterns('ecommerce_crm.catalog.views',
    url(r'^$', 'index'),
    url(r'^select_sub_category/', 'select_sub_category'),
    url(r'^jsreverse/', 'jsreverse'),
    url(r'^select_item/', 'select_item'), 
    url(r'^bill_cal/','bill_cal'),
    url(r'^list_products/','list_products'),
    url(r'^previous_value/','previous_value'),
    url(r'^order_added_success/','order_added_success'),
    url(r'^change_request/','change_request'),
    url(r'^price_per_unit/','price_per_unit'),
    url(r'^select_type/','select_type'),
    url(r'^nonpaymentorderofsession/','nonpaymentorderofsession'),
    url(r'^nonpaymentordersuccess/','nonpaymentordersuccess'),
)


urlpatterns += patterns('ecommerce_crm.catalog.request_change',
   url(r'^request_save/','request_save'),
   url(r'^list_requests/','list_request'),
   url(r'^view_request/','view_request'),
   url(r'^accept_request/','accept_request'),
   url(r'^reject_request/','reject_request'),
   url(r'^permission_denied/','permission_denied'),
)

src/ecommerce_crm/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from reports.register_generator import GenerateRegister
from reports.search import SearchResult
from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'ecommerce_crm.catalog.views.index', name='home'),
    url(r'^catalog/', include('ecommerce_crm.catalog.urls')),
    url(r'^useraccounts/', include('useraccounts.urls')),
    url(r'^print/', include('ecommerce_crm.prints.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/','ecommerce_crm.reports.views.search_form'),
    url(r'^search_result/', SearchResult.as_view(), name='search_result'),
    url(r'^save_fields', 'ecommerce_crm.reports.views.save_fields'),
    url(r'^list_saved_registers', 'ecommerce_crm.reports.views.list_saved_registers'),
    url(r'daily_result', 'ecommerce_crm.reports.register.daily_report_result', name='daily_report_result'),
    url(r'consultancy_funds_report', 'ecommerce_crm.reports.register.consultancy_funds_report', name='consultancy_funds_report'),    
    url(r'tds_report', 'ecommerce_crm.reports.register.tds_report_result', name='tds_report_result'),    
    url(r'payment_report', 'ecommerce_crm.reports.register.payment_register', name='payment_register'),
    url(r'suspense_clearance_register', 'ecommerce_crm.reports.register.suspense_clearance_register'),
    url(r'servicetax', 'ecommerce_crm.reports.register.servicetax_register'),
    url(r'^main_register', 'ecommerce_crm.reports.register.main_register', name='main_register'),
    url(r'^proforma_register', 'ecommerce_crm.reports.register.proforma_register'),
    url(r'^non_payment_register', 'ecommerce_crm.reports.register.non_payment_register'),
    url(r'^client_register', 'ecommerce_crm.reports.register.client_register', name='client_register'),
    url(r'^material_report', 'ecommerce_crm.reports.register.material_report'),
    url(r'^lab_report', 'ecommerce_crm.reports.register.lab_report'),
    url(r'^suspense_register', 'ecommerce_crm.reports.register.suspense_register'),
    url(r'^registered_users', 'ecommerce_crm.reports.register.registered_users'),
    url(r'^filter_sub_category/', 'ecommerce_crm.reports.views.filter_sub_category'),
    url(r'^bill/', 'ecommerce_crm.prints.views.bill'),
    url(r'^suspense_bill/', 'ecommerce_crm.prints.views.suspense_bill'),
    url(r'^quoted_bill/', 'ecommerce_crm.prints.views.quoted_bill'),
    url(r'^tax/', 'ecommerce_crm.prints.views.tax'),
    url(r'^bills/', include('ecommerce_crm.bills.urls')),
    url(r'^suspense/', include('ecommerce_crm.suspense.urls')),
    url(r'^generate_register/', GenerateRegister.as_view(), name='view_register'),
    url(r'^history/','ecommerce_crm.reports.previous_history.history'),
    url(r'^details/','ecommerce_crm.reports.previous_history.details'),
    url(r'^proforma_details/','ecommerce_crm.reports.previous_history.proforma_details'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^voucher/', include('ecommerce_crm.voucher.urls')),
    url(r'^receipt/', 'ecommerce_crm.prints.views.receipt'),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^programmeletter/', 'ecommerce_crm.programmeletter.views.programmeletter'),
    url(r'pending_clearance_register', 'ecommerce_crm.reports.register.pending_clearance_register'),
    url(r'tada_register', 'ecommerce_crm.reports.register.tada_register'),
    url(r'tada_othercharges_register', 'ecommerce_crm.reports.register.tada_othercharges_register'),
    url(r'client_details_according_to_amount', 'ecommerce_crm.reports.register.client_details_according_to_amount'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

src/ecommerce_crm/catalog/models.py
"""
models of catalog are..
"""
from django.db import models

from django.forms import ModelForm

import useraccounts

from django.contrib.auth.models import User

from django.http import HttpResponse

from mptt.models import MPTTModel, TreeForeignKey

import mptt.fields

from django.core.exceptions import ValidationError

import datetime

from tinymce.models import HTMLField

from ecommerce_crm.config import _BUYER
from ecommerce_crm.config import _DELIVERY_ADDRESS
from ecommerce_crm.config import _IS_DEBIT
from ecommerce_crm.config import _PURCHASED_ITEMS
from ecommerce_crm.config import _QTY
from ecommerce_crm.config import _REFERENCE
from ecommerce_crm.config import _REFERENCE_DATE


class mCategory(models.Model):
    """
    This class defines the name of category and parent category of product
    """
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', blank=True, null=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return unicode(self.name)


class Unit(models.Model):
    """
    This class defines a unit variable for Categories
    """
    unit = models.CharField(max_length=100)
    def __unicode__(self):
        return '%s' % (self.unit)


class Category(MPTTModel):
    """
    This class defines the name of category, its parent and unit of each category
    the organisation deals with
    """
    name = models.CharField(max_length=100)
    parent = TreeForeignKey('self', null=True, blank=True, \
        related_name="children")
    unit = models.ForeignKey(Unit, null=True, blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __unicode__(self):
        return '%s' % self.name


class Product(models.Model):
    """
    This class defines the name of product, category, price of eact item of
    that product and the organisation with which user deals
    """
    name = models.CharField(max_length=500)
    category = mptt.fields.TreeForeignKey(Category, related_name="products")
    price_per_unit = models.IntegerField(blank=True,null=True)
    organisation = models.ForeignKey('useraccounts.AdminOrganisations')
    def __unicode__(self):
        return self.name


class Attributes(models.Model):
    """
    This class defines the features of product
    """
    name = models.CharField(max_length=200)
    is_number = models.BooleanField(default = True)
    is_string = models.BooleanField(default = False)

    class Meta:
        verbose_name_plural = "Attributes"

    def __unicode__(self):
        return self.name


class ModeOfPayment(models.Model):
    """
    This class defines the details about user, its organisation, along with
    total discount and payment of job, and mode of payment
    """
    method = models.CharField(max_length=25)

    class Meta:
        verbose_name_plural = "Modes of payment"

    def __unicode__(self):
        return self.method


class Surcharge(models.Model):

    """
    This class defines the type of taxes, value, validation of taxes
    mentioning the startdate and end date
    """
    tax_name = models.CharField(max_length=200)
    value = models.FloatField()
    taxes_included = models.BooleanField(default = False)
    tax_effected_from = models.DateField(null = True)
    tax_valid_till = models.DateField(null = True)
    Remark = models.CharField(max_length=1000, null = True)
    def __unicode__(self):
         return self.tax_name


class PurchaseOrder(models.Model):
    """
    This class defines members for orders to placed by users
    """
    buyer = models.ForeignKey(User,verbose_name= _BUYER)
    is_debit = models.BooleanField(default = False, verbose_name = _IS_DEBIT)
    reference = models.CharField(max_length=200, verbose_name=_REFERENCE)
    reference_date = models.DateField(blank=True, null=True, verbose_name=_REFERENCE_DATE)
    delivery_address = models.CharField(max_length=500, blank=True, null=True,\
        verbose_name = _DELIVERY_ADDRESS)
    organisation = models.ForeignKey('useraccounts.AdminOrganisations', default=1)
    date_time = models.DateField(auto_now_add=True)
    purchase_order_time = models.TimeField(auto_now_add=True)
    total_discount = models.IntegerField(default = 0)
    tds = models.IntegerField(default = 0)
    mode_of_payment = models.ForeignKey(ModeOfPayment)
    cheque_dd_number = models.CharField(max_length=50, blank=True)
    cheque_dd_date = models.DateField(max_length=50, blank=True, null=True)
    type_of_service = models.ForeignKey('useraccounts.OrganisationType')
    is_active = models.BooleanField(default = True)
    def save(self, *args, **kwargs):

        surchages = Surcharge.objects.filter(taxes_included=1)

        if surchages:
            pass
        else:
            raise ValidationError('No Active Taxes. Unable to add Order')
        from ecommerce_crm.voucher.models import FinancialSession
        now = datetime.datetime.now()
        financialsession = FinancialSession.objects.\
        values('id','session_start_date','session_end_date')
        for value in financialsession:
            start_date = value['session_start_date']
            end_date = value['session_end_date']
            if start_date <= now.date() <= end_date:
                session_id = value['id']
        try:
            session_id
            super(PurchaseOrder, self).save(*args, **kwargs)
        except:
            raise ValidationError('No Current Financial Session')
    def __unicode__(self):
        return '%s' % (self.id)


class PurchasedItem(models.Model):
    """
    This class defines members for items purchased in a purchase order
    """
    purchase_order = models.ForeignKey(PurchaseOrder)
    price_per_unit = models.IntegerField()
    qty = models.IntegerField(verbose_name = _QTY)
    price = models.IntegerField()
    item = models.ForeignKey(Product)
    def save(self, *args, **kwargs):
        try:
            if self.purchase_order:
                self.price = self.price_per_unit * self.qty
                super(PurchasedItem, self).save(*args, **kwargs)
        except:
            raise ValidationError('No Active Taxes. Unable to add Items')

    def __unicode__(self):
        return '%s' % (self.item) + ' - ' '%s' % (self.purchase_order)

    class Meta:
        verbose_name = _PURCHASED_ITEMS
        verbose_name_plural = _PURCHASED_ITEMS


class Catalog(models.Model):
    """
    This class defines the features, value of product
    """
    attribute = models.ForeignKey(Attributes)
    value = models.CharField(max_length=200)
    product = models.ForeignKey(Product)
    def __unicode__(self):
        return self.attribute.name


class TaxesApplied(models.Model):
    """
    This class defines the taxes applied on the purchase order
    """
    purchase_order = models.ForeignKey(PurchaseOrder)
    surcharge = models.ForeignKey(Surcharge)
    surcharge_name = models.CharField(max_length=500)
    surcharge_value = models.FloatField()
    tax = models.IntegerField()
    def __unicode__(self):
        return "%s" % (self.surcharge)


class Bill(models.Model):
    """
    This class defines the grand total of the purchase order
    """
    purchase_order = models.ForeignKey(PurchaseOrder)
    delivery_charges = models.IntegerField()
    total_cost = models.IntegerField()
    totalplusdelivery = models.IntegerField()
    total_tax = models.IntegerField()
    grand_total = models.IntegerField()
    amount_received = models.IntegerField()


class HeaderFooter(models.Model):
    """
    This class is used to add, edit or delete Header and Footer to be 
    used for Bills in the organisation
    """
    header = HTMLField()
    footer = HTMLField()
    is_active = models.BooleanField(default = False)
    def save(self, *args, **kwargs):
        if self.is_active == True:
            temp = HeaderFooter.objects.filter(is_active=1)
            if temp:
                HeaderFooter.objects.filter(is_active=1).\
                update(is_active=0)
                super(HeaderFooter, self).save(*args, **kwargs)
            else:
                super(HeaderFooter, self).save(*args, **kwargs)
        else:
            super(HeaderFooter, self).save(*args, **kwargs)
    def __unicode__(self):
        return '%s' % (self.id)

    class Meta:
        verbose_name_plural = "Header and Footer"


class SurchargePaid(models.Model):
    surcharge = models.ForeignKey(Surcharge)
    value = models.IntegerField()
    date = models.DateField(auto_now_add = True)
    def __unicode__(self):
        return '%s paid on ' % (self.surcharge, self.date)


class ChangeRequest(models.Model):
    """
    This class defines members which enables the user to select a purchase order
    to request a change in the Bill Amount
    """
    purchase_order_of_session = models.IntegerField()
    from ecommerce_crm.voucher.models import FinancialSession
    session = models.ForeignKey(FinancialSession)
    previous_total = models.IntegerField()
    new_total = models.IntegerField()
    description = models.CharField(max_length=100)
    initiator = models.CharField(max_length=50)
    initiation_date = models.DateField(auto_now_add = True)


class RequestSurchargeChange(models.Model):
    """
    This class defines members for requesting the change in a Bill
    """
    change_request = models.ForeignKey(ChangeRequest)
    surcharge = models.ForeignKey(TaxesApplied)
    previous_value = models.IntegerField()
    new_value = models.IntegerField()


class RequestStatus(models.Model):
    """
    This class defines members to specify status of the chnage request
    """
    change_request = models.ForeignKey(ChangeRequest)
    confirmed = models.BooleanField(default=False)
    cancelled = models.BooleanField(default=False)
    request_response = models.DateField(null = True)


class NonPaymentOrder(models.Model):
    """
    This class defines members for the purchase orders to be completed in 
    future but the date is not determined
    """

src/templates/catalog/change_form.html
{% extends 'base.html' %}
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Change Request</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  {% if messages %}
                <div class="alert alert-success">
                    <p>{{ messages }}</p> 
                </div>
                {% endif %}
  <div class='change_request'>
    <table>
       <tr>
          <th>Client:</th>
          <td>{{details.purchase_order__buyer__first_name}}&nbsp;{{details.purchase_order__buyer__last_name}}
           &nbsp;{{details.purchase_order__buyer__customer__title}}</td>
       </tr>
       <tr>
           <th>Address:</th>
           <td>{{details.purchase_order__buyer__customer__address__street_address}}&nbsp;
              {{details.purchase_order__buyer__customer__address__district}}</td>
          </tr>
          <tr>
           <th>Mode Of Payment:</th>
           <td>{{details.purchase_order__mode_of_payment__method}}</td>
       </tr>
   </table>
</div>
<table>
    <tr>
        <td>
        </td>
    </tr>
</table>
<form action='{% url 'ecommerce_crm.catalog.request_change.request_save' %}?order_id={{order_id}}&session={{session}}' method='POST'>
    <table class="changeform">
        {% csrf_token %}
        <tr>
            <th><label>Previous Total:</label></th>
            <th><input name="previous_total" class='form-control' value="{{bill.grand_total}}" readonly="readonly" type="text"
                id="previous_total" /></th>
            </tr>
            <tr>
                <th><label>Surcharge:</label></th>
                <th><label>Previous:</label></th>
                <th><label>New:</label></th>
            </tr>
            {% for value in surcharge %}
            <tr>
                <td><input name="surcharge" class='form-control' value="{{value.surcharge__tax_name}}" readonly="readonly" type="text" /></td> 
                <td><input name="previous_value" class='form-control' value="{{value.tax}}" readonly="readonly" type="text" id="previous_{{value.id}}" /></td> 
                <td><input name="new_value" type="number" class='form-control new_value' placeholder="New Value" id="{{value.id}}" /></td>
            </tr>
            {% endfor %}
            <tr>
                <th><label>New Total:</label></th>
                <th><input name="new_total" class='form-control' readonly="readonly" type="text" id="new_total" /></th>
            </tr>
        </table>
        <label for="id_description">Description:</label>
        <textarea cols="40" name="description" rows="5" placeholder="Description"></textarea>
        <input type="submit" class="btn btn-info btn-large" value="Send Request" name='button1' id='button1' />
    </form>
    {% endblock %}
</body>
</html>

src/templates/catalog/change_request.html
{% extends "base.html" %} {% load staticfiles %}
<html>
<head>
    {% block title %}
    <title>Form</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <form method="POST" action={% url 'ecommerce_crm.catalog.views.change_request' %} >
        {% if errors %}
        <div class="alert alert-danger">
            {{ errors }}
        </div>
        {% endif %}
        {% csrf_token %}
        <table> 
            {{form.as_table}}
        </table>
        <input type="submit" class="btn btn-info btn-large" value="Submit" id="button1">
    </form>
    {% endblock %}
</body>
</html>

src/templates/catalog/list_products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
    {% load staticfiles %}
    <link href="{% static 'css/product_list.css' %}" media="all" rel="stylesheet" type="text/css">
</head>
<body>

    <div class = "wrapper">
        <h2 class="parent-category"> {{root_name.name}} </h2>
        {% for result in result %}
        <div class="products-list">
            <h2 class="parent-category"> {{ result.0 }} </h2>
            {% for category in result.1 %}
            <h4>{{ category.name }}</h4>
            <div class="product-container">
                {% for product in result.2 %}
                {% if product.category_id == category.id %}
                <h4 class="product-head"> <span class="product-name"> {{ product.name | safe}} </span>
                    <span class="product-price">&#8377; {{ product.price_per_unit }}/- </span> </h4>
                    
                    {% endif %}
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </body>
    </html>

src/templates/catalog/list_request.html
{% extends 'base_register.html' %}
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>
        Requests
    </title>
    {% endblock %}
</head>
<body>
{% block content %}
<div class = 'list-registers'>
    <div class='view-list'>
        <table border='1px'>
            <tr>
                <th>Request Id</th>
                <th>Description</th>
                <th>Status</th>
                <th>Option</th>
            </tr>
            {% for values in list %}
            <tr>
                <td>{{values.id}}</td>
                <td>{{values.description}}</td>
                <td>{{values.request_status}}</td>
                <td><a href = '{% url 'catalog.request_change.view_request' %}?id={{values.id}}'>View</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div> 
{% endblock %}
</body>
</html>

src/templates/catalog/nonpaymentsuccess.html
{% extends 'base_register.html' %}
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Order added</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Order added <span class='green'>
      Successfully</span></p>
      <table>
      <tr>
           <th>Non Payment Order Id:</th>
           <td>{{order_id}}</td>
       </tr>
       <tr>
          <th>Client:</th>
          <td>{{details.buyer__first_name}}&nbsp;{{details.buyer__last_name}}
           &nbsp;{{details.buyer__customer__title}}</td>
       </tr>
       <tr>
           <th>Address:</th>
           <td>{{details.buyer__customer__address__street_address}}&nbsp;
              {{details.buyer__customer__address__district}}</td>
          </tr>
          <tr>
           <th>Letter:</th>
           <td>No. {{data.reference}} dated {{data.reference_date}}</td>
       </tr>
       <tr>
           <th>Site:</th>
           <td>{{data.delivery_address}}</td>
       </tr>
       <tr>
           <th>Material:</th>
           <td>{{data.item_type}}</td>
       </tr>
   </table>
   </div>
   {% endblock %}
</body>
</html>

src/templates/catalog/order_added_success.html
{% extends 'base_register.html' %}
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Order added</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Order added <span class='green'>
      Successfully</span></p>
      <table>
       <tr>
          <th>Client:</th>
          <td>{{details.purchase_order__buyer__first_name}}&nbsp;{{details.purchase_order__buyer__last_name}}
           &nbsp;{{details.purchase_order__buyer__customer__title}}</td>
       </tr>
       <tr>
           <th>Address:</th>
           <td>{{details.purchase_order__buyer__customer__address__street_address}}&nbsp;
              {{details.purchase_order__buyer__customer__address__district}}</td>
          </tr>
          <tr>
           <th>Mode Of Payment:</th>
           <td>{{details.purchase_order__mode_of_payment__method}}</td>
       </tr>
   </table>
   <div class='order-success-options'>
    <table>
        <tr>
           <th colspan='3'><h3>Options</h3></th>
       </tr>
       <tr>
          {% if details.receipt_no_of_session %}
           <td><a target="_blank" href = '{% url 'ecommerce_crm.prints.views.receipt' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Receipt"></a></td>
           {% else %}
           <td><a target="_blank" href = '{% url 'ecommerce_crm.prints.views.receipt' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Confirm"></a></td>
           {% endif %}
           <td></td>
           <td><a target="_blank" href = '{% url 'ecommerce_crm.voucher.views.voucher_show' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Voucher"></a></td>
       </tr>
       <tr>
           <td><a target="_blank" href = '{% url 'ecommerce_crm.prints.views.bill' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Bill"></a></td>
           <td></td>
           <td><a target="_blank" href = '{% url 'ecommerce_crm.prints.views.tax' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Tax Details"></a></td>
       </tr>
       {% if suspense_flag == 1 %}
       <tr>
           <td></td>
           <td><a target="_blank" href = '{% url 'ecommerce_crm.prints.views.suspense_bill' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Suspense Bill"></a></td>
           <td></td>
       </tr>
       {% endif %}
           </table>
       </div>
   </div>
   {% endblock %}
</body>
</html>

src/templates/catalog/product_list_form.html
{% extends "base.html" %}
{% load i18n %} {% load staticfiles %} 

<html>
<head>
{% block title %}
<title>Form</title>
{% endblock %}
</head>
<body>
  {% block content %}
  <form class="form-horizontal" role="form" method="POST"  action='{% url 'ecommerce_crm.catalog.views.list_products' %}' >
  	<div class="form-group">
       	{% csrf_token %}
       		<table class="form_class">
            {{form.as_table}}
          </table>
   	      <input type="submit" class="btn btn-info btn-large" value="Submit" name='button1' id='button1'>
 	</div>
</form>
   {% endblock %}
 </body>
 </html>

src/templates/catalog/request_success.html
{% extends 'base_register.html' %}
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Order added</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Request Sent <span class='green'>
      Successfully</span></p>
  </div>
  {% endblock %}
</body>
</html>

src/templates/catalog/response_change_email.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <h2 text-align='center' >Request for a change</h2>
  <p>Change Request <b>{{request_status}}</b> by <b>{{user.first_name}} {{user.last_name}}</b></p>
  <table border='1px'>
    <tr>
      <th>Entity</th>
      <th>Previous Value</th>
      <th>New Value</th>
    </tr>
    <tr>
      <td>Total</td>
      <td><font color='red'>{{previous_total.previous_total}}
      </font></td>
      <td><font  color='green'>{{new_total.new_total}}</font></td>
    </tr>
    {% for value in surcharge_diff %}
    <tr>
      <td>{{value.surcharge__surcharge__tax_name}}</td>
      <td><font color='red'>{{value.previous_value}}
      </font></td>
      <td><font color='green'>{{value.new_value}}
      </font></td>
    </tr>
    {% endfor %}
  </table>
  <p><b>Note:</b> This message is generated by Ecommerce_CRM software. No need to reply this.</p>
</body>
</html>

src/templates/catalog/view_request.html
{% extends 'base_register.html' %}
{% load i18n %} {% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
 {% block title %}
 <title>Request</title>
 {% endblock %}
</head>
<body>
  {% block content %}
  <div class = 'list-registers'>
   <div class='view-list'>
    <table>
     <tr>
      <th>Initiator:</th>
      <td>{{initiator.initiator}}</td>
    </tr>
    <tr>
      <th>Date of Initiation:</th>
      <td>{{initiation_date.initiation_date}}</td>
    </tr>
    {% if request_status != 'Waiting' %}
    <tr>
      {% if request_status == 'Confirmed' %}
      <th>Date of Confirmation:</th>
      {% else %}
      <th>Date of Cancellation:</th>
      {% endif %}
      <td>{{request_response.request_response}}</td>
    </tr>
    {% endif %}
    <tr>
      <th>Status:</th>
      <td>{{request_status}}</td>
      <tr>
        <th>Description:</th>
        <td>{{description.description}}</td>
      </tr>
    </table>
    <div class="diff">
     <h4>Detailed Diff</h4>
     <table border='1px'>
      <tr>
       <th>Entity</th>
       <th>Previous Value</th>
       <th>New Value</th>
     </tr>
     <tr>
       <td>Total</td>
       <td><font id="previous_value">{{previous_total.previous_total}}
       </font></td>
       <td><font  id="new_value">{{new_total.new_total}}</font></td>
     </tr>
     {% for value in surcharge_diff %}
     <tr>
      <td>{{value.surcharge__surcharge__tax_name}}</td>
      <td><font id="previous_value">{{value.previous_value}}
      </font></td>
      <td><font id="new_value">{{value.new_value}}
      </font></td>
    </tr>
    {% endfor %}

  </table>
  <div class = "options">
   <a class = 'accept_request' href = '{{id}}'>
    <input type="button" class="btn btn-info btn-large"
    name="" value="Request Response"></a>
  </div>
</div>
</div>
</div>
{% endblock %}
</body>
</html>